### ISSUE TITLE
Loops in functions that modify large areas of storage

### ISSUE THREAD

**Issue by pauliax** [ether-arts/ether-arts#1]
There are several loops in the contract which can eventually grow so large as to make future operations of the contract cost too much gas to fit in a block. 

Example:
EAO_mission.sol  function AssignMissionWinners
It has 6 for loops that iterate over a dynamic length array and changes the state inside it.

Be careful when using loops (for/while), as if it iterates through many items, the execution may exceed the block gas limit, consume all the gas provided and fail. Carefully test how many items at maximum you can pass to such functions to make it successful. Also, take into consideration that test networks (example, Rinkeby) could have different block gas limit than the main network.

**Comment by ether-arts** [comment]
Thank you for reporting potential problem. We will perform a full inspection of the loops in the smart contract and check the potential problems. Please tell me your metamask wallet address. Thank you!
admin@ether-arts.io

**Comment by pauliax** [comment]
My address is 0x09Cf79Bdf8F68739979C8c825C103A7538Bd4f4b
I would like to finish reviewing the contracts but they pretty much contain no comments and some parts are difficult. Is there a documentation or something explaining the expected behaviour of the contracts?

**Comment by ether-arts** [comment]
Sorry for the inconvenience. I'll update contract files after making additional comments on it. But it takes time. please wait for day. Thank you.

**Comment by pauliax** [comment]
When the rewards will be distributed?
